_BASE_: "./LVISv0.5-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml"
MODEL:
  META_ARCHITECTURE: "DualRCNN_image"
  BACKBONE:
    MOMENTUM: 0.99
  ROI_HEADS:
    RARE_CAT_FILE: "lvis_categories_lists/lvis0.5_rare_common30_cats.txt"
TEST:
  EVAL_PERIOD: 5000
SEED: 6481261